# Generated by Django 5.1.6 on 2025-03-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_product_price_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
