# Generated by Django 5.1.6 on 2025-04-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
