# Generated by Django 5.1.6 on 2025-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_myuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="orders/receipts/"),
        ),
    ]
